In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.metrics import accuracy_score, confusion_matrix, mean_absolute_error,r2_score,classification_report

In [3]:
df = pd.read_csv('Metro_Interstate_Traffic_Volume.csv')

In [4]:
df

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume
0,NaN,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545
1,NaN,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516
2,NaN,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767
3,NaN,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026
4,NaN,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918
...,...,...,...,...,...,...,...,...,...
48199,NaN,283.45,0.0,0.0,75,Clouds,broken clouds,2018-09-30 19:00:00,3543
48200,NaN,282.76,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 20:00:00,2781
48201,NaN,282.73,0.0,0.0,90,Thunderstorm,proximity thunderstorm,2018-09-30 21:00:00,2159
48202,NaN,282.09,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 22:00:00,1450
48203,NaN,282.12,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 23:00:00,954

In [6]:
df = df.sample(10000,random_state=42)

In [7]:
df

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume
35748,NaN,289.49,0.0,0.0,1,Fog,fog,2017-07-28 07:00:00,6364
147,NaN,279.35,0.0,0.0,1,Clear,sky is clear,2012-10-08 21:00:00,2030
24362,NaN,291.39,0.0,0.0,36,Clouds,scattered clouds,2016-06-22 00:00:00,708
35495,NaN,294.02,0.0,0.0,90,Thunderstorm,thunderstorm,2017-07-19 22:00:00,2029
11010,NaN,268.69,0.0,0.0,64,Mist,mist,2013-12-27 09:00:00,3734
...,...,...,...,...,...,...,...,...,...
39270,NaN,281.82,0.0,0.0,75,Clouds,broken clouds,2017-11-26 16:00:00,4933
45850,NaN,301.79,0.0,0.0,1,Clear,sky is clear,2018-07-14 13:00:00,4218
21888,NaN,273.08,0.0,0.0,90,Clouds,overcast clouds,2016-03-18 05:00:00,2577
32239,NaN,273.52,0.0,0.0,40,Clouds,scattered clouds,2017-03-31 08:00:00,5944
9572,NaN,279.38,0.0,0.0,64,Clouds,broken clouds,2013-10-19 12:00:00,5031

In [8]:
df.isnull().sum()

holiday                9986
temp                      0
rain_1h                   0
snow_1h                   0
clouds_all                0
weather_main              0
weather_description       0
date_time                 0
traffic_volume            0
dtype: int64

In [9]:
df['holiday'].value_counts()

holiday
Thanksgiving Day             3
Independence Day             2
Columbus Day                 2
Labor Day                    2
Washingtons Birthday         2
Martin Luther King Jr Day    1
Christmas Day                1
Veterans Day                 1
Name: count, dtype: int64

In [10]:
df['holiday'] = df['holiday'].fillna('Normal day')

In [11]:
df['holiday'].value_counts()

holiday
Normal day                   9986
Thanksgiving Day                3
Independence Day                2
Columbus Day                    2
Labor Day                       2
Washingtons Birthday            2
Martin Luther King Jr Day       1
Christmas Day                   1
Veterans Day                    1
Name: count, dtype: int64

In [13]:
df['holiday'].isnull().sum()

np.int64(0)

In [15]:
x = df.drop(columns = ['traffic_volume'])
y = df['traffic_volume']

In [17]:
x = pd.get_dummies(x)

In [18]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=42)

In [19]:
dcr = DecisionTreeRegressor(max_depth=10,random_state=42)

In [20]:
dcr.fit(xtrain, ytrain)

DecisionTreeRegressor(max_depth=10, random_state=42)

In [21]:
ypred = dcr.predict(xtest)

In [24]:
print("R2 Score:", r2_score(ytest, ypred))
print("MAE:", mean_absolute_error(ytest, ypred))

R2 Score: 0.0589789677862963
MAE: 1639.1651376885202